name: Deploy Shashank's Profile Flet app to GitHub Pages

on:
  push:
    branches: [ main ] # Triggers build every time you push code to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  UV_PYTHON: 3.12

  # https://flet.dev/docs/reference/environment-variables
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build:
    name: Build web app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        
      - name: Cleanup build directory
        run: rm -rf build/ assets/app.zip dist/ .venv/ .uv/ requirements.txt

      - name: Build app
        shell: bash
        run: |
          uv run flet build web --yes --compile-pyo --verbose --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: build/web
          name: web-build-artifact
          retention-days: 20

  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # deploy only on push to main
    needs: build  # wait for the "build" job to get done
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact